#:kivy 2.3.1
<HomeScreen@Screen>:
    name: "home_screen"

    MDLabel:
        text: "Home Screen"
        font_style: "H4"
        halign: "center"
        pos_hint: {"center_y": 0.8}

    #Logout Button
    MDRaisedButton:
        text: "Logout"
        pos_hint: {"center_x": 0.5, "center_y": 0.4}
        on_release: app.login_screen()


    NavigationBar:
        

# Navigation bar Component
<NavigationBar@BoxLayout>:
    ## 4 Buttons: Home, Scorecard/Round History, Golf Courses, //(Profile/Account Settings) <-- This one will be implemented in different location>
    orientation: "horizontal"
    size_hint_y: None 
    pos_hint: {"center_x": 0.5}  
    height: "50dp"
    padding: "10dp"
    spacing: "10dp"
    canvas.before:
        Color:
            rgba: utils.get_color_from_hex("#228B22")
        Rectangle:
            pos: self.pos
            size: self.size
    Widget:
        size_hint_x: 1
    MDRaisedButton:
        text: "A"
        size_hint_x: "30dp"
        width: "50dp"
        #on_release: app.scorecard_screen()
    MDRaisedButton:
        text: "Home"
        size_hint_x: "10dp"
        width: "20dp"
        on_release: app.home_screen()
    MDRaisedButton:
        text: "C"
        size_hint_x: "30dp"
        width: "50dp"
        #on_release: app.courses_screen()
    Widget:
        size_hint_x: 1
        #on_release: app.courses_screen()


